In [ ]:
#gerekli kütüphaneyi ekliyoruz

In [39]:
import pandas as pd

In [ ]:
#verisetimizi excel dosyamızdan çekiyoruz

In [40]:
df = pd.read_excel("sahibinden_arabaverileri2.xlsx")
df.drop("Unnamed: 0", axis=1, inplace=True)
df_2 = df.copy()
df_3 = df.copy()

In [41]:
df_2

,marka,yıl,yakıt,vites,KM,kasatipi,motor_gücü,motor_hacmi,çekiş,renk,garanti,plaka_uyruk,kimden,takas,durumu
0,Renault,2012,Dizel,Yarı Otomatik,220.00,Sedan,110,1461,Önden Çekiş,Beyaz,Hayır,Türkiye (TR) Plakalı,Galeriden,Evet,İkinci El
1,Dacia,2014,Dizel,Manuel,78.32,Hatchback 5 kapı,90,1461,Önden Çekiş,Gri,Hayır,Türkiye (TR) Plakalı,Sahibinden,Hayır,İkinci El
2,Honda,2020,Benzin & LPG,Yarı Otomatik,2.70,Sedan,125,1597,Önden Çekiş,Beyaz,Evet,Türkiye (TR) Plakalı,Galeriden,Hayır,İkinci El
3,BMW,2003,Benzin,Otomatik,235.30,Sedan,333,4398,Arkadan İtiş,Mavi,Hayır,Türkiye (TR) Plakalı,Galeriden,Hayır,İkinci El
4,Renault,2017,Dizel,Manuel,103.00,Hatchback 5 kapı,75,1461,Önden Çekiş,Beyaz,Evet,Türkiye (TR) Plakalı,Galeriden,Hayır,İkinci El
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,Toyota,2008,Dizel,Manuel,290.00,Sedan,90,1364,Önden Çekiş,Gri,Hayır,Türkiye (TR) Plakalı,Galeriden,Evet,İkinci El
546,Ford,2011,Benzin & LPG,Otomatik,110.00,Hatchback 5 kapı,96,1388,Önden Çekiş,Mor,Hayır,Türkiye (TR) Plakalı,Galeriden,Evet,İkinci El
547,Renault,2016,Dizel,Manuel,77.00,Sedan,110,1461,Önden Çekiş,Gümüş Gri,Hayır,Türkiye (TR) Plakalı,Galeriden,Evet,İkinci El
548,Fiat,2016,Dizel,Manuel,135.00,Sedan,95,1248,Önden Çekiş,Beyaz,Hayır,Türkiye (TR) Plakalı,Galeriden,Evet,İkinci El
549,Fiat,2000,Benzin & LPG,Manuel,234.00,Sedan,71,1372,Önden Çekiş,Gümüş Gri,Hayır,Türkiye (TR) Plakalı,Sahibinden,Hayır,İkinci El

In [42]:
df_2.columns

Index(['marka', 'yıl', 'yakıt', 'vites', 'KM', 'kasatipi', 'motor_gücü',
       'motor_hacmi', 'çekiş', 'renk', 'garanti', 'plaka_uyruk', 'kimden',
       'takas', 'durumu'],
      dtype='object')

In [ ]:
#etiketleme işlemi için sklearn içindeki kütüphaneyi kullanmamız gerekiyor
#ayrıca preprocessing kütüphanesinden OneHotEncoder sınıfınıda kullanıcaz.

In [43]:
from sklearn import preprocessing
le = preprocessing.LabelEncoder()
onehotencoder = preprocessing.OneHotEncoder()

In [ ]:
#get_dummies fonksiyonu ile "çekiş,yakıt,vites,kasatipi,kimden,durumu" satırlarının özniteliklerini ikili değerlere dönüştürücez

In [44]:
df_2['çekiş']=pd.Categorical(df['çekiş'])
dfDummies = pd.get_dummies(df_2['çekiş'], prefix='')
df_2.drop("çekiş",axis=1, inplace=True)

df_2['yakıt']=pd.Categorical(df['yakıt'])
dfDummies2 = pd.get_dummies(df_2['yakıt'], prefix='')
df_2.drop("yakıt",axis=1, inplace=True)

df_2['vites']=pd.Categorical(df['vites'])
dfDummies3 = pd.get_dummies(df_2['vites'], prefix='')
df_2.drop("vites",axis=1, inplace=True)

df_2['plaka_uyruk']=pd.Categorical(df['plaka_uyruk'])
dfDummies4 = pd.get_dummies(df_2['plaka_uyruk'], prefix='')
df_2.drop("plaka_uyruk",axis=1, inplace=True)

df_2['kasatipi']=pd.Categorical(df['kasatipi'])
dfDummies5 = pd.get_dummies(df_2['kasatipi'], prefix='')
df_2.drop("kasatipi",axis=1, inplace=True)

df_2['kimden']=pd.Categorical(df['kimden'])
dfDummies6 = pd.get_dummies(df_2['kimden'], prefix='')
df_2.drop("kimden",axis=1, inplace=True)

df_2['durumu']=pd.Categorical(df['durumu'])
dfDummies7 = pd.get_dummies(df_2['durumu'], prefix='')
df_2.drop("durumu",axis=1, inplace=True)


df_3 =pd.concat([df_2, dfDummies,dfDummies2,dfDummies3,dfDummies4,dfDummies5,dfDummies6,dfDummies7], axis=1)

In [ ]:
#marka ve renk sütunlarında çok fazla seçenek olduğu için bu sutunları fit_transform fonksiyonu ile etiketliyorum
#le.classes_ fonksiyonu ile etiketlediğimiz verilerin neler olduğuna bakabiliriz.

In [45]:
df_3["marka"] = le.fit_transform(df_2.marka)
le.classes_

array(['Alfa Romeo\xa0', 'Audi\xa0', 'BMW\xa0', 'Chevrolet\xa0',
       'Citroën\xa0', 'Dacia\xa0', 'Daewoo\xa0', 'Fiat\xa0', 'Ford\xa0',
       'Honda\xa0', 'Hyundai\xa0', 'Kia\xa0', 'Mazda\xa0',
       'Mercedes - Benz\xa0', 'Mini\xa0', 'Mitsubishi\xa0', 'Nissan\xa0',
       'Opel\xa0', 'Peugeot\xa0', 'Renault\xa0', 'Rover\xa0', 'Seat\xa0',
       'Skoda\xa0', 'Suzuki\xa0', 'Tofaş\xa0', 'Toyota\xa0',
       'Volkswagen\xa0', 'Volvo\xa0'], dtype=object)

In [46]:
df_3["renk"] = le.fit_transform(df_2.renk)
le.classes_

array(['Bej', 'Beyaz', 'Bordo', 'Füme', 'Gri', 'Gümüş Gri', 'Kahverengi',
       'Kırmızı', 'Lacivert', 'Mavi', 'Mor', 'Sarı', 'Siyah', 'Turkuaz',
       'Yeşil', 'Şampanya'], dtype=object)

In [47]:
df_3

,marka,yıl,KM,motor_gücü,motor_hacmi,renk,garanti,takas,_4WD (Sürekli),_Arkadan İtiş,...,_Coupe,_Hatchback 3 kapı,_Hatchback 5 kapı,_MPV,_Sedan,_Station Wagon,_Galeriden,_Sahibinden,_Sıfır,_İkinci El
0,19,2012,220.00,110,1461,1,Hayır,Evet,0,0,...,0,0,0,0,1,0,1,0,0,1
1,5,2014,78.32,90,1461,4,Hayır,Hayır,0,0,...,0,0,1,0,0,0,0,1,0,1
2,9,2020,2.70,125,1597,1,Evet,Hayır,0,0,...,0,0,0,0,1,0,1,0,0,1
3,2,2003,235.30,333,4398,9,Hayır,Hayır,0,1,...,0,0,0,0,1,0,1,0,0,1
4,19,2017,103.00,75,1461,1,Evet,Hayır,0,0,...,0,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,25,2008,290.00,90,1364,4,Hayır,Evet,0,0,...,0,0,0,0,1,0,1,0,0,1
546,8,2011,110.00,96,1388,10,Hayır,Evet,0,0,...,0,0,1,0,0,0,1,0,0,1
547,19,2016,77.00,110,1461,5,Hayır,Evet,0,0,...,0,0,0,0,1,0,1,0,0,1
548,7,2016,135.00,95,1248,1,Hayır,Evet,0,0,...,0,0,0,0,1,0,1,0,0,1
549,7,2000,234.00,71,1372,5,Hayır,Hayır,0,0,...,0,0,0,0,1,0,0,1,0,1

In [ ]:
#takas ve garanti sütunlarında iki seçenek var, ya True yada False.
#bu sütunlarıda loc fonksiyonu ile sayısal verilere çevirdim

In [48]:
df_3.loc[df_2.takas=='Evet',"takas"] = 1
df_3.loc[df_2.takas=='Hayır',"takas"] = 0
df_3.loc[df_2.garanti=='Evet',"garanti"] = 1
df_3.loc[df_2.garanti=='Hayır',"garanti"] = 0

In [49]:
df_3

,marka,yıl,KM,motor_gücü,motor_hacmi,renk,garanti,takas,_4WD (Sürekli),_Arkadan İtiş,...,_Coupe,_Hatchback 3 kapı,_Hatchback 5 kapı,_MPV,_Sedan,_Station Wagon,_Galeriden,_Sahibinden,_Sıfır,_İkinci El
0,19,2012,220.00,110,1461,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,1
1,5,2014,78.32,90,1461,4,0,0,0,0,...,0,0,1,0,0,0,0,1,0,1
2,9,2020,2.70,125,1597,1,1,0,0,0,...,0,0,0,0,1,0,1,0,0,1
3,2,2003,235.30,333,4398,9,0,0,0,1,...,0,0,0,0,1,0,1,0,0,1
4,19,2017,103.00,75,1461,1,1,0,0,0,...,0,0,1,0,0,0,1,0,0,1
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
545,25,2008,290.00,90,1364,4,0,1,0,0,...,0,0,0,0,1,0,1,0,0,1
546,8,2011,110.00,96,1388,10,0,1,0,0,...,0,0,1,0,0,0,1,0,0,1
547,19,2016,77.00,110,1461,5,0,1,0,0,...,0,0,0,0,1,0,1,0,0,1
548,7,2016,135.00,95,1248,1,0,1,0,0,...,0,0,0,0,1,0,1,0,0,1
549,7,2000,234.00,71,1372,5,0,0,0,0,...,0,0,0,0,1,0,0,1,0,1

In [ ]:
#verileri excel dosyasına atıyoruz ve ön_işleme işlemlerini burda bitirmiş oluyoruz.

In [50]:
df_3.to_excel("sahibinden_arabaverileri3.xlsx")